Fade in fade out when switching websites [fix for #47, #9]
sindresorhus/Plash pull request #81
Opened 2021-04-22 22:52 UTC by uruha-komachin

Using another SSWebView, `webview2` in WebViewController to fix issue #47 and #9.

Animation time is set to 0.5 seconds for both fade in and fade out effect. I'm not sure if the animation time brings the best user experience, but please advise and I can make corresponding changes.

Btw, amazing application! 😉

2021-04-24 14:52 UTC, sindresorhus commented
Thanks for working on this. I think the code needs to be better abstracted. Having to handle either web view in every single place is not going to be sustainable.

2021-04-26 20:22 UTC, uruha-komachin commented
@sindresorhus Hi, I've tried to abstract a little bit more on switching the background webView and the foreground one. Hope that's more clear and maintainable now.

2021-05-08 10:56 UTC, sindresorhus commented
The PR doesn't compile.

2021-05-08 10:57 UTC, sindresorhus requested changes

2021-05-08 10:57 UTC, sindresorhus commented on Plash/WebViewController.swift
> +		internalOnLoaded(error, webView as! SSWebView)
Don't force-cast.

2021-05-08 10:57 UTC, sindresorhus commented on Plash/WebViewController.swift
> +	var loadInBackground = false
```suggestion
	var isLoadedInBackground = false
```

2021-05-08 10:58 UTC, sindresorhus commented
I think this PR generally needs more work. Try to refactor it a bit more. Also make sure you try out a lot of different combination of use-cases, to route out bugs.

2021-08-20 23:42 UTC, sindresorhus commented
Closing for lack of activity and it's too far from being mergeable.

2021-08-20 23:42 UTC, closed without merging